version: '2'
services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=DB_PW
      - MYSQL_DATABASE=easyapp
      - MYSQL_USER=easyapp
      - MYSQL_PASSWORD=DB_PW

  application:
    image: easyappointments
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    command: dev
    ports:
      - ${APP_HOST}:${APP_PORT}:80
    environment:
      - DB_HOST=database:3306
      - APP_URL=https://easyappointments.dtrautwein.eu
    depends_on:
      - database
    env_file:
      - .env
    restart: always
